version: "3"
services:

  database:
    image: "postgres:14.2"
    volumes:
      - argus_db_data:/var/lib/postgresql/data/
    env_file:
      - .env.local
    container_name: argus_database
    ports:
      - "5432:5432"

  jaeger:
    image: jaegertracing/all-in-one:1.29
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

volumes:
  argus_db_data:
