name: Go Build and Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'  # Adjust to your Go version

      - name: Install make
        run: sudo apt-get install make

      - name: Build
        run: make build

      - name: Test
        run: make test
